print("Howdy git!\n")
print("           .--._.--.            ") 
print("          ( O     O )           ")
print("          /   . .   \           ")
print("         .`._______.`.          ")
print("        /(           )\         ")
print("      _/  \  \   /  /  \_       ")
print("   .~   `  \  \ /  /  `   ~.    ")
print("  {    -.   \  V  /   .-    }   ")
print(" __`.    \  |  |  |  /    .`_ _ ")
print(">_       _} |  |  | {_       _< ")
print(" /. - ~ ,_-`  .^.  `-_, ~ - .\  ")
print("         `-`|/   \|`-`          ")
